version: "3.8"

services:
  pt-agent:
    image: pt-agent:latest
    container_name: pt-agent
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
      - /vol1/1000/Media:/vol1/1000/Media
